// Generated by https://quicktype.io

export interface Client {
  id:            string;
  partnerName:   string;
  createPowwi:   number;
  minCreditTerm: number;
  maxCreditTerm: number;
  minAmmount:    number;
  maxAmmount:    number;
}
