// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface FirstStep {
  tipoDocumento:   TipoDocumento;
  numeroDocumento: string;
  celular:         string;
}

export interface TipoDocumento {
  id: number;
  description: string
}



