// Generated by https://quicktype.io

export interface SecondStep {
  primerNombre:   string;
  primerApellido: string;
  dia:            string;
  mes:            string;
  anio:           string;
  email:          string;
}
