// Generated by https://quicktype.io

import { Document } from "./documents.model";

export interface SignDocument {
  actionStrategyPattern: string;
  otp:                   string;
  id:                    string;
  contratoMutuo:         Document;
}

